credentials:
  uri: 'neo4j+s://738a9212.databases.neo4j.io'
  user: '738a9212'
  password: 'LLdrXoQtv7noKIxLg41vZCb0I9nyuDUnjatXeSEcpxs'
  database: '738a9212'
  instance_id: '738a9212'
  instance_name: 'Co-author Graph'